### PR TITLE
Add build script.

### PR DESCRIPTION
**Pull request by sbts**
build_quaternion.sh allows a single command to build (and optionally update the local git repo) quaternion

### CODE REVIEW

**Comment by KitsuneRal** [comment]
What you're trying to do is more than halfway of packaging the application. Maybe make a full-fledged debian/ directory then? Somebody else would bring in the .spec file for Fedora, and will be good to go on 80% of the user base (Arch is already covered externally, by the way).

**Comment by KitsuneRal** [comment]
...and I promise to have some build counter so that the build packages could be properly upgraded then :)

**Comment by elsieholmes** [comment]
>  .spec file for Fedora

And for OpenSUSE. These are **different** distros. Plus, you can build packages for different distros on SUSE's OBS.

**Comment by KitsuneRal** [comment]
We now have a Flatpak, the package is submitted for inclusion into Debian, and the work on packaging for OBS is ongoing - see https://github.com/QMatrixClient/Quaternion/issues/211. Thanks for your help anyway!

**Pull request closed without merging**
