### PR TITLE
Linkify URLs enclosed in angle brackets

### PR DESCRIPTION
**Pull request by ryco117**
Attempt fix for issue https://github.com/QMatrixClient/Quaternion/issues/171

### CODE REVIEW

**Comment by KitsuneRal** [comment]
Thanks for the PR. What if the URL is only prepended by a left bracket but doesn't have a trailing `>`; or conversely, what if there's no `<` but there is `>`?
I wonder if a lookahead for `&gt;` would help you to filter out the trailing `>`.

**Comment by ryco117** [comment]
Corrected some comments and valid URI regex. Used lookahead to enforce that it cant end with "&gt;" if it doesn't start with '<' (ie nothing is linkified now if only one bracket)

screenshot from 2017-09-30 22-05-20

**Comment by KitsuneRal** [comment]
Sorry for taking time, the week is very packed... I'm puzzled by your choice to not linkify URLs if the surrounding brackets are unbalanced. Do you have a certain reason for that? I actually should have been more explicit in my original comment - my take is that URLs should be linkified regardless of whether `<` and `>` exist around them. Or am I missing something?

**Comment by ryco117** [comment]
Originally I went out of my way to do it like that because thats what I thought you wanted (you know what they say about when you assume..) but I'm now seeing that allowing it to linkify when it has an unmatched closing bracket (ie "http://test.test/test>" ) will result in an issue in HTML (=> "http://test.test/test&gt;") where the regex parser will have no indication that the "&gt;" is not part of the URI (so it'll linkify into the wrong address)

**Comment by KitsuneRal** [comment]
Uhm, shouldn't `>` be percent-escaped if it occurs in a URL?

Interestingly, the github linkifier only includes the literal `>`, not `&gt;`. Doesn't look neither proper, nor consistent anyway.

**Comment by KitsuneRal** [comment]
Oh, I start getting it. Since HTML-escaping comes first, the trailing `>` is converted to `&gt;`, which in turn is incorrectly parsed as a part of a URL by the linkifier :-\

**Comment by KitsuneRal** [comment]
...so that means that the regex should treat the trailing `&gt;` as an HTML-escaped `>` and not include it in the URL. I guess it's better to move to the Matrix room with all that.

**Comment by ryco117** [comment]
screenshot from 2017-10-05 22-32-38

Simpler code/regex, more desirable result

**Comment by KitsuneRal** [comment]
Yes - almost perfect! But I think that `\\b` should be enough _before the URL_ is superfluous because `\\s` before `\\w` implies `\\b`. Or am I again missing something?

**Pull request merged**
